# Cirrus CI for FreeBSD builds

env:
  CIRRUS_CLONE_DEPTH: 1

only_if: $CIRRUS_BRANCH == 'master'

# There's no need to compile if no source files were changed
skip: "!changesInclude('.cirrus.yml', '*.cc', '*.c', '*.h', 'Makefile', '*.mk', 'configure.ac', 'config.default.in')"

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  dependency_script:
    - pkg install -y lzlib bzip2 autoconf gcc gmake
  matrix:
    - name: FreeBSD SDL2 Build
      build_script:
        - pkg install -y sdl2 sdl2_mixer freetype2 miniupnpc
        - autoconf && ./configure
        - gmake
    - name: FreeBSD Server Build
      build_script:
        - autoconf && ./configure --enable-server
        - gmake
    - name: FreeBSD Makeobj Build
      build_script:
        - pkg install -y png pkgconf
        - autoconf && ./configure
        - cd makeobj
        - gmake
