env:
  CIRRUS_CLONE_DEPTH: 1

# Windows
task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    CIRRUS_SHELL: powershell
  dependency_script:
    - $msys2 = (Get-Location).Drive.Root + "msys64"
    - git clone --depth 1 https://github.com/msys2/msys2-ci-base.git $msys2
    - $env:PATH = $msys2;$env:PATH
    - pacman -Syu --noconfirm --noprogressbar
    - pacman -Su --noconfirm --noprogressbar mingw-w64-i686-zlib mingw-w64-i686-bzip2 autoconf mingw-w64-i686-gcc make
  matrix:
    - name: Windows MinGW SDL2 Build
      build_script:
        - pacman -S --noconfirm --noprogressbar mingw-w64-i686-SDL2 mingw-w64-i686-SDL2_mixer mingw-w64-i686-freetype mingw-w64-i686-miniupnpc
        - autoconf && ./configure
        - make
    - name: Windows MinGW GDI Build
      build_script:
        - pacman -S --noconfirm --noprogressbar mingw-w64-i686-freetype mingw-w64-i686-miniupnpc
        - autoconf && ./configure
        - make
    - name: Windows MinGW Server Build
      build_script:
        - autoconf && ./configure --enable-server
        - make
    - name: Windows MinGW Makeobj Build
      build_script:
        - pacman -S --noconfirm --noprogressbar mingw-w64-i686-libpng mingw-w64-i686-pkg-config
        - autoconf && ./configure
        - cd makeobj
        - make

# MacOS
task:
  osx_instance:
    image: mojave-xcode-10.2
  dependency_script:
    - ruby -e $("curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install")
    - brew install autoconf
  matrix:
    - name: MacOS SDL2 Build
      build_script:
        - brew install sdl2 sdl2_mixer freetype miniupnpc
        - autoconf && ./configure
        - make
    - name: MacOS Server Build
      build_script:
        - autoconf && ./configure --enable-server
        - make
    - name: MacOS Makeobj Build
      build_script:
        - brew install libpng pkg-config
        - autoconf && ./configure
        - cd makeobj
        - make
